/**
 * Utility to translate Vietnamese raw system messages generated by backend into i18n keys.
 */
export const translateSystemMessage = (text, t) => {
  if (!text) return '';

  const patterns = [
    {
      regex: /^(.*) đã tham gia đoạn chat nhóm$/,
      key: 'systemMessages.joinedGroup',
      mapVars: (m) => ({ user: m[1] })
    },
    {
      regex: /^(.*) đã rời khỏi đoạn chat nhóm$/,
      key: 'systemMessages.leftGroup',
      mapVars: (m) => ({ user: m[1] })
    },
    {
      regex: /^(.*) muốn thêm (.*) vào trong đoạn chat nhóm$/,
      key: 'systemMessages.wantsToAdd',
      mapVars: (m) => ({ requestingUser: m[1], userToAdd: m[2] })
    },
    {
      regex: /^Yêu cầu bị từ chối bởi quản trị viên$/,
      key: 'systemMessages.requestDenied',
      mapVars: () => ({})
    },
    {
      regex: /^(.*) đã đổi biệt danh của (.*) thành (.*)$/,
      key: 'systemMessages.changedNickname',
      mapVars: (m) => ({ changingUser: m[1], changedUser: m[2], nickname: m[3] })
    },
    {
      regex: /^(.*) đã xóa biệt danh của (.*)$/,
      key: 'systemMessages.clearedNickname',
      mapVars: (m) => ({ changingUser: m[1], changedUser: m[2] })
    },
    {
      regex: /^(.*) đã đổi biểu tượng cảm xúc của đoạn chat$/,
      key: 'systemMessages.changedEmoji',
      mapVars: (m) => ({ user: m[1] })
    },
    {
      regex: /^(.*) đã đổi màu chủ đề đoạn chat$/,
      key: 'systemMessages.changedThemeColor',
      mapVars: (m) => ({ user: m[1] })
    },
    {
      regex: /^(.*) đã xóa màu chủ đề đoạn chat$/,
      key: 'systemMessages.removedThemeColor',
      mapVars: (m) => ({ user: m[1] })
    },
    {
      regex: /^(.*) đã tạo một cuộc thăm dò ý kiến$/,
      key: 'systemMessages.createdPoll',
      mapVars: (m) => ({ user: m[1] })
    },
    {
      regex: /^(.*) đã thêm lựa chọn mới vào cuộc thăm dò ý kiến$/,
      key: 'systemMessages.addedPollOption',
      mapVars: (m) => ({ user: m[1] })
    },
    {
      regex: /^(.*) đã thay đổi bình chọn từ (.*) sang (.*) trong cuộc thăm dò ý kiến$/,
      key: 'systemMessages.changedVoteFromTo',
      mapVars: (m) => ({ user: m[1], removed: m[2], added: m[3] })
    },
    {
      regex: /^(.*) đã bình chọn cho (.*) trong cuộc thăm dò ý kiến$/,
      key: 'systemMessages.votedFor',
      mapVars: (m) => ({ user: m[1], options: m[2] })
    },
    {
      regex: /^(.*) đã gỡ bình chọn cho (.*) trong cuộc thăm dò ý kiến$/,
      key: 'systemMessages.removedVoteFor',
      mapVars: (m) => ({ user: m[1], options: m[2] })
    },
    {
      regex: /^(.*) đã bình chọn thêm cho (.*) trong cuộc thăm dò ý kiến$/,
      key: 'systemMessages.votedAdditionallyFor',
      mapVars: (m) => ({ user: m[1], options: m[2] })
    },
    {
      regex: /^(.*) đã thay đổi bình chọn trong cuộc thăm dò ý kiến$/,
      key: 'systemMessages.changedVote',
      mapVars: (m) => ({ user: m[1] })
    }
  ];

  try {
    for (const { regex, key, mapVars } of patterns) {
      const match = text.match(regex);
      if (match) {
        return t(key, mapVars(match));
      }
    }
  } catch (error) {
    console.error('Error translating system message:', error);
  }

  return text;
};
